### ISSUE TITLE
Refresh token grant type is currently not supported by the apifest-client

### ISSUE THREAD

**Issue by vmuth85** [apifest/apifest-client#3]
I'm trying to test the "refresh token" mechanism as described in the documentation under point:  "4.5.4 Refresh token grant type" but the TokenRequest.java doesn't contain a 'refresh_token' attribute and the according Getter and Setter. Same story in the OAuthServer.java interface and the OAuthClient.java.
Could you provide this feature please? I don't want to use my local version of this client...
Thanks in advance!

**Comment by apostolterziev** [comment]
Will do shortly. Thanks for noticing!

**Comment by rossitsaborissova** [comment]
I'm really sorry for the long delay.
