### ISSUE TITLE
Passthrough of the SSLContext to the ResteasyClient

### ISSUE THREAD

**Issue by vmuth85** [apifest/apifest-client#4]
The OAuthClient must urgently speak over https with the ApiFest server due to prevent a man-in-the-middle attack.
Initializing the OAuthClient with a 'https' URL will lead to a:

> javax.net.ssl.SSLHandshakeException

What I don't want to do is to add my certificate to each JVM's trust store that is using the OAuthClient. A better approach would be a mechanism that allows me to provide a SSLContext to the OAuthClient, so my application would do the job.

Could you add a second constructor like 

>  public OAuthClient(String oauthUrl, SSLContext sslContext)

or just a setter method for the SSLContext?

Maybe you can even implement a sophisticated mechanism for dealing with certifactes.jks?!
Just to get an idea of what I'm talking about, I've forked your client with a sample implementation.
You can use the whole code if you want: https://github.com/vmuth85/apifest-client

**Comment by apostolterziev** [comment]
Hi,

There is a reason why the Client doesn't "speak" https. it's intended to be
used by admin tools and trusted applications in the DMZ. You should NEVER
expose the oauth server interface to an entrusted network. Can you give a
simple description of your usecase so we can figure out why you need this.

Api

**Comment by vmuth85** [comment]
Hi,
thank you for the explanation, I wasn't aware of the fact, that your client was build for administrational purposes only. I've implemented my own client that is speaking via SSL with the Mapping Server. In order to request an access token, my client extends the OAuthClient and the only method I'm using from the OAuthClient is the `OAuthTokenResponse fetchToken(TokenRequest tokenRequest)`. Well, you are right, under those circumstances it doesn't make any sense, to let the OAuthClient speak 'https'.

**Comment by apostolterziev** [comment]
Usually the best way to approach this is to have an endpoint in YOUR
application that allows token fetching. This way it'll be consistent with
your API and the oauth server will be hidden in the DMZ.

Ex. Suppose you expose a restful API using JSON as the transport format.
You can expose an /fetch-token andpoint that accepts a json object instead
of a form-url-encoded payload. This way you get a consistent API and make
it easier for your clients and hide all dangerous oauth server endpoints.

Api

**Comment by vmuth85** [comment]
Thanks for the suggestion, I will try it!
